GKI: scripts: stop if export is __init or __exit
Strip problematic __init or __exit tags from exported functions, but
stop with script failure so that the human can intercede and run a
build to determine the side effects and inspect if other changes are
required.  The script can be run again with the _original_ build log
file to complete the operation.

Add a check to confirm that the git files that are changed match the
expected files to be adjusted and warn if they are different.  Submit
the whole overlapping set as a means of allowing continuation of the
script.

Manual Test involves generating a false build log, for example:

 :: undefined reference to `cam_cdm_intf_init_module'
 :: undefined reference to `cam_cdm_intf_exit_module'

and letting it modify sources that have __init or __exit tags to
prove out the functionality.

  $ add_EXPORT_SYMBOL_GPL < build_output_file
  Reading symbols
  Finding symbols in the current tree
  Editing the files that contain the symbols
  INFO: export cam_cdm_intf_exit_module in drivers/cam_cdm/cam_cdm_intf.c
  int __init cam_cdm_intf_init_module(void) -> int cam_cdm_intf_init_module(void)
  ERROR: scrubbing __init from function in drivers/cam_cdm/cam_cdm_intf.c
         Compile check, possibly edit drivers/cam_cdm/cam_cdm_intf.c and friends.
         Then re-run add_EXPORT_SYMBOL_GPL to complete.
  INFO: export cam_cdm_intf_init_module in drivers/cam_cdm/cam_cdm_intf.c
  drivers/cam_cdm/cam_cdm_intf.c
  FAILED: could not complete task
  $ git diff
  . . .
  -int __init cam_cdm_intf_init_module(void)
  +int cam_cdm_intf_init_module(void)
  . . .
  +EXPORT_SYMBOL_GPL(cam_cdm_intf_init_module);
  . . .
  +EXPORT_SYMBOL_GPL(cam_cdm_intf_exit_module);
  . . .
  $ add_EXPORT_SYMBOL_GPL < build_output_file
  Reading symbols
  Finding symbols in the current tree
  Editing the files that contain the symbols
  INFO: cam_cdm_intf_exit_module found and already exported
  INFO: cam_cdm_intf_init_module found and already exported
  DONE
  WARNING: list of files in git different from files we expected to edit

Signed-off-by: Mark Salyzyn <salyzyn@google.com>
SideEffects: script was a one shot thing, now it allows continuation.
Test: manually create the condition and log since typically rare.
Change-Id: Ia5a719529317cc3679093a88f5eabdaf086233de

diff --git a/scripts/gki/add_EXPORT_SYMBOL_GPL b/scripts/gki/add_EXPORT_SYMBOL_GPL
--- a/scripts/gki/add_EXPORT_SYMBOL_GPL
+++ b/scripts/gki/add_EXPORT_SYMBOL_GPL
@@ -140,6 +140,23 @@ DATA="`grep -Fr \"${SYMBOLS_PLUS_TRACE}\" * |
          skip_arch_files`"
 echo "Editing the files that contain the symbols" >&2
 TMP=`mktemp -d`
+
+[ 'USAGE: report_strip_of_tag tag
+
+Report if a problematic function segment tag is stripped from the file
+
+expects ${F}, ${TMP}, ${TAB}, ${RED} and ${NORMAL} to be defined' ]
+report_strip_of_tag() {
+  if diff --side-by-side --suppress-common-lines ${F} ${TMP}/${F##*/} |
+    sed -n "s/\(.*[ ${TAB}]\)\(__${1}\)\([^a-zA-Z0-9_].*[^ ${TAB}]\)[ ${TAB}]\{1,\}|[ ${TAB}]\{1,\}/\1${BLUE}\2${NORMAL}\3 -> /p" |
+       grep __${1} >&2; then
+    echo "${RED}ERROR${NORMAL}: scrubbing __${1} from function in ${F}" >&2
+    echo "       Compile check, possibly edit ${F} and friends." >&2
+    echo "       Then re-run ${progname} to complete." >&2
+    echo FAILED
+  fi
+}
+
 for s in ${SYMBOLS}; do
   # Already there?
   if echo "${DATA}" |
@@ -220,6 +237,10 @@ done |
            N
            /\(\n}\);*$/ {
              s//\1/
+             s/^\([^\n]*[^\n ${TAB}]\|\)[ ${TAB}]\{1,\}__\(init\|exit\)[ ${TAB}]\{1,\}\([^\n]*(\)/\1 \3/
+             s/^\([^\n]*[^\n ${TAB}]\|\)[ ${TAB}]\{1,\}__\(init\|exit\)\([^ ${TAB}a-zA-Z0-9_][^\n]*(\)/\1 \3/
+             s/^__\(init\|exit\)[ ${TAB}]\{1,\}\([^\n]*(\)/\2/
+             s/^__\(init\|exit\)\([^ ${TAB}a-zA-Z0-9_][^\n]*(\)/\2/
              a \
                new${EXPORT_SYMBOL}(${s});
              b next1
@@ -263,6 +284,8 @@ done |
            }' >${TMP}/${F##*/} &&
       ! cmp -s ${F} ${TMP}/${F##*/} &&
       [ -s ${TMP}/${F##*/} ] &&
+      report_strip_of_tag init &&
+      report_strip_of_tag exit &&
       cp ${TMP}/${F##*/} ${F} &&
       echo INFO: export ${s} in ${F} >&2 ||
       (
@@ -279,8 +302,23 @@ ret=${?}
 rm -rf ${TMP}
 if [ 0 -ne ${ret} ]; then
   echo "DONE" >&2
-  if [ -z "${FILES}" ]; then
+  GIT_FILES="`git diff |
+                sed -n 's@^diff --git a/\(.*\) b/\1$@\1@p' |
+                sort -u`"
+  if [ -z "${GIT_FILES}" ]; then
+    echo "${BLUE}WARNING${NORMAL}: no changes to commit" >&2
+    if [ -n "${FILES}" ]; then
+      echo "         but we altered files!" >&2
+    fi
     exit
+  fi
+  SEMI=""
+  if [ X"${GIT_FILES}" != X"`echo ${FILES} | tr ' ' '\n' | sort -u`" ]; then
+    SEMI="Semi-"
+    FILES=`echo ${FILES} ${GIT_FILES} |
+             tr ' ' '\n' |
+             sort -u`
+    echo "${BLUE}WARNING${NORMAL}: list of files in git different from files we expected to edit, continuation?" >&2
   fi
 
   AUTHOR_NAME="`git config user.name`"
@@ -293,6 +331,7 @@ if [ 0 -ne ${ret} ]; then
       echo "${1##*/}" |
         sed "s@[-_]@ @g
              s@   *@ @g
+             s@adelva@Alistair Delva@
              s@\(saravana\)k@\1 kannan@
              s@salyzyn@mark &@
              s@hridya@& valsaraju@
@@ -339,7 +378,7 @@ if [ 0 -ne ${ret} ]; then
 
 <edit>
 
-Automatically generated by ${0##*/}
+${SEMI}Automatically generated by ${0##*/}
 
 The following symbols are exported:
 `echo \"${SYMBOLS}\" |
